// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Layout": {
    "title": "Key Realty",
    "description": "Developed by Benjamin Paniagua"
  },
  "LanguageSwitcher": {
    "label": "Change language",
    "english": "English",
    "spanish": "Spanish"
  },
  "NotFoundPage": {
    "title": "404 - Page Not Found",
    "description": "Please, check the browser's address bar or use the navigation to go to a known page.",
    "goBackHome": "Go back home"
  },
  
  "NavBar": {
    "links": [
      { "name": "Home", "href": "/" },
      { "name": "Buy", "href": "/properties?type=buy" },
      { "name": "Sell", "href": "/properties?type=sell" },
      { "name": "Rent", "href": "/properties?type=rent" },
      { "name": "About us", "href": "/about" },
      { "name": "Contact us", "href": "/contact" }
    ]
  },
  
  "Footer": {
    "copyright": "Copyright © {year} Benjamin Paniagua Rojas"
  }
};
export default messages;